# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 507b785278e6cf2d902ec03ec41bc24feaeac7f08afa3e44edd14af86998091394f71f729f9f9f759789958b32ab4d449b7687176379040085606901bfc952d9

test:
  secret_key_base: 31ac9bb6749f7e92db45a3f3826680514562b2f13f9994be7fb107f90dbb8b46d97a967c74ac10a3bd969668fb66c6f123ac620f0520ba7a7f7f9c1a76f545bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
